In [1]:
import pandas as pd
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

In [2]:
np.set_printoptions(linewidth=np.inf)

In [3]:
nsamples = 20
data = pd.DataFrame(
    columns=["v1", "v2", "t"],
    index=pd.date_range(start="2023-01-01", freq="D", periods=nsamples),
)

data["v1"] = np.arange(1, nsamples + 1)
data["v2"] = data["v1"] + 0.1
data["t"] = data["v1"] + 0.01

y_d = data[["t"]].copy(deep=True)
x_d = data[["v1", "v2"]].copy(deep=True)

print(data.shape)

print(data.tail(), end="\n\n")

print(data.head())

(20, 3)
            v1    v2      t
2023-01-16  16  16.1  16.01
2023-01-17  17  17.1  17.01
2023-01-18  18  18.1  18.01
2023-01-19  19  19.1  19.01
2023-01-20  20  20.1  20.01

            v1   v2     t
2023-01-01   1  1.1  1.01
2023-01-02   2  2.1  2.01
2023-01-03   3  3.1  3.01
2023-01-04   4  4.1  4.01
2023-01-05   5  5.1  5.01


In [20]:
data_np = data["t"].to_numpy()
print(data_np.shape)
data_np = np.hstack([np.array(4 * [None], dtype=float), data_np])
print(data_np.shape)
data_np

(20,)
(24,)


array([  nan,   nan,   nan,   nan,  1.01,  2.01,  3.01,  4.01,  5.01,  6.01,  7.01,  8.01,  9.01, 10.01, 11.01, 12.01, 13.01, 14.01, 15.01, 16.01, 17.01, 18.01, 19.01, 20.01])

In [30]:
# window_shape in  sliding_window_view =  window_shape * number of features
data_np = data["t"].to_numpy()
data_np = np.hstack([np.array(4 * [None], dtype=float), data_np])
s_window = sliding_window_view(data_np.flatten(), window_shape=4)[:-1]
print(s_window.shape)
s_window

(20, 4)


array([[  nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,  1.01],
       [  nan,   nan,  1.01,  2.01],
       [  nan,  1.01,  2.01,  3.01],
       [ 1.01,  2.01,  3.01,  4.01],
       [ 2.01,  3.01,  4.01,  5.01],
       [ 3.01,  4.01,  5.01,  6.01],
       [ 4.01,  5.01,  6.01,  7.01],
       [ 5.01,  6.01,  7.01,  8.01],
       [ 6.01,  7.01,  8.01,  9.01],
       [ 7.01,  8.01,  9.01, 10.01],
       [ 8.01,  9.01, 10.01, 11.01],
       [ 9.01, 10.01, 11.01, 12.01],
       [10.01, 11.01, 12.01, 13.01],
       [11.01, 12.01, 13.01, 14.01],
       [12.01, 13.01, 14.01, 15.01],
       [13.01, 14.01, 15.01, 16.01],
       [14.01, 15.01, 16.01, 17.01],
       [15.01, 16.01, 17.01, 18.01],
       [16.01, 17.01, 18.01, 19.01]])

In [31]:
exo_np = data[["v1", "v2"]].to_numpy()
print(exo_np.shape)
exo_np

(20, 2)


array([[ 1. ,  1.1],
       [ 2. ,  2.1],
       [ 3. ,  3.1],
       [ 4. ,  4.1],
       [ 5. ,  5.1],
       [ 6. ,  6.1],
       [ 7. ,  7.1],
       [ 8. ,  8.1],
       [ 9. ,  9.1],
       [10. , 10.1],
       [11. , 11.1],
       [12. , 12.1],
       [13. , 13.1],
       [14. , 14.1],
       [15. , 15.1],
       [16. , 16.1],
       [17. , 17.1],
       [18. , 18.1],
       [19. , 19.1],
       [20. , 20.1]])

In [32]:
np.hstack([exo_np, s_window])

array([[ 1.  ,  1.1 ,   nan,   nan,   nan,   nan],
       [ 2.  ,  2.1 ,   nan,   nan,   nan,  1.01],
       [ 3.  ,  3.1 ,   nan,   nan,  1.01,  2.01],
       [ 4.  ,  4.1 ,   nan,  1.01,  2.01,  3.01],
       [ 5.  ,  5.1 ,  1.01,  2.01,  3.01,  4.01],
       [ 6.  ,  6.1 ,  2.01,  3.01,  4.01,  5.01],
       [ 7.  ,  7.1 ,  3.01,  4.01,  5.01,  6.01],
       [ 8.  ,  8.1 ,  4.01,  5.01,  6.01,  7.01],
       [ 9.  ,  9.1 ,  5.01,  6.01,  7.01,  8.01],
       [10.  , 10.1 ,  6.01,  7.01,  8.01,  9.01],
       [11.  , 11.1 ,  7.01,  8.01,  9.01, 10.01],
       [12.  , 12.1 ,  8.01,  9.01, 10.01, 11.01],
       [13.  , 13.1 ,  9.01, 10.01, 11.01, 12.01],
       [14.  , 14.1 , 10.01, 11.01, 12.01, 13.01],
       [15.  , 15.1 , 11.01, 12.01, 13.01, 14.01],
       [16.  , 16.1 , 12.01, 13.01, 14.01, 15.01],
       [17.  , 17.1 , 13.01, 14.01, 15.01, 16.01],
       [18.  , 18.1 , 14.01, 15.01, 16.01, 17.01],
       [19.  , 19.1 , 15.01, 16.01, 17.01, 18.01],
       [20.  , 20.1 , 16.01, 17

In [23]:
sliding_window_view(test_data_np.flatten(), window_shape=4 * 3)[::3]

array([[ 81.  ,  81.1 ,  81.01,  82.  ,  82.1 ,  82.01,  83.  ,  83.1 ,  83.01,  84.  ,  84.1 ,  84.01],
       [ 82.  ,  82.1 ,  82.01,  83.  ,  83.1 ,  83.01,  84.  ,  84.1 ,  84.01,  85.  ,  85.1 ,  85.01],
       [ 83.  ,  83.1 ,  83.01,  84.  ,  84.1 ,  84.01,  85.  ,  85.1 ,  85.01,  86.  ,  86.1 ,  86.01],
       [ 84.  ,  84.1 ,  84.01,  85.  ,  85.1 ,  85.01,  86.  ,  86.1 ,  86.01,  87.  ,  87.1 ,  87.01],
       [ 85.  ,  85.1 ,  85.01,  86.  ,  86.1 ,  86.01,  87.  ,  87.1 ,  87.01,  88.  ,  88.1 ,  88.01],
       [ 86.  ,  86.1 ,  86.01,  87.  ,  87.1 ,  87.01,  88.  ,  88.1 ,  88.01,  89.  ,  89.1 ,  89.01],
       [ 87.  ,  87.1 ,  87.01,  88.  ,  88.1 ,  88.01,  89.  ,  89.1 ,  89.01,  90.  ,  90.1 ,  90.01],
       [ 88.  ,  88.1 ,  88.01,  89.  ,  89.1 ,  89.01,  90.  ,  90.1 ,  90.01,  91.  ,  91.1 ,  91.01],
       [ 89.  ,  89.1 ,  89.01,  90.  ,  90.1 ,  90.01,  91.  ,  91.1 ,  91.01,  92.  ,  92.1 ,  92.01],
       [ 90.  ,  90.1 ,  90.01,  91.  ,  91.1 ,  91.01,

In [ ]:
def reduce_window(
    self, y_train: pd.DataFrame, x_hog: pd.DataFrame
) -> Tuple[np.ndarray, np.ndarray]:
    y_train_np = y_train.to_numpy().flatten()
    y_lags = np.hstack([np.array(self.window_len * [None], dtype=float), y_train_np])
    y_lags = sliding_window_view(y_lags.flatten(), window_shape=self.window_len)
    y_lags_train = y_lags[:-1]
    if x_hog is not None:
        x_hog_np = x_hog.to_numpy()
        x_data = np.hstack([x_hog_np, y_lags_train])
    else:
        x_data = y_lags_train
    return x_data, y_train_np, y_lags[-1:]