In [1]:
import pandas as pd
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

In [2]:
np.set_printoptions(linewidth=np.inf)

In [3]:
nsamples = 20
data = pd.DataFrame(
    columns=["v1", "v2", "t"],
    index=pd.date_range(start="2023-01-01", freq="D", periods=nsamples),
)

data["v1"] = np.arange(1, nsamples + 1)
data["v2"] = data["v1"] + 0.1
data["t"] = data["v1"] + 0.01

y_d = data[["t"]].copy(deep=True)
x_d = data[["v1", "v2"]].copy(deep=True)

print(data.shape)

print(data.tail(), end="\n\n")

print(data.head())

(20, 3)
            v1    v2      t
2023-01-16  16  16.1  16.01
2023-01-17  17  17.1  17.01
2023-01-18  18  18.1  18.01
2023-01-19  19  19.1  19.01
2023-01-20  20  20.1  20.01

            v1   v2     t
2023-01-01   1  1.1  1.01
2023-01-02   2  2.1  2.01
2023-01-03   3  3.1  3.01
2023-01-04   4  4.1  4.01
2023-01-05   5  5.1  5.01


In [6]:
data_np = data.to_numpy()
data_np

array([[ 1.  ,  1.1 ,  1.01],
       [ 2.  ,  2.1 ,  2.01],
       [ 3.  ,  3.1 ,  3.01],
       [ 4.  ,  4.1 ,  4.01],
       [ 5.  ,  5.1 ,  5.01],
       [ 6.  ,  6.1 ,  6.01],
       [ 7.  ,  7.1 ,  7.01],
       [ 8.  ,  8.1 ,  8.01],
       [ 9.  ,  9.1 ,  9.01],
       [10.  , 10.1 , 10.01],
       [11.  , 11.1 , 11.01],
       [12.  , 12.1 , 12.01],
       [13.  , 13.1 , 13.01],
       [14.  , 14.1 , 14.01],
       [15.  , 15.1 , 15.01],
       [16.  , 16.1 , 16.01],
       [17.  , 17.1 , 17.01],
       [18.  , 18.1 , 18.01],
       [19.  , 19.1 , 19.01],
       [20.  , 20.1 , 20.01]])

In [8]:
# window_shape in  sliding_window_view =  window_shape * number of features

sliding_window_view(data_np.flatten(), window_shape=4 * 3)

array([[ 1.  ,  1.1 ,  1.01,  2.  ,  2.1 ,  2.01,  3.  ,  3.1 ,  3.01,  4.  ,  4.1 ,  4.01],
       [ 1.1 ,  1.01,  2.  ,  2.1 ,  2.01,  3.  ,  3.1 ,  3.01,  4.  ,  4.1 ,  4.01,  5.  ],
       [ 1.01,  2.  ,  2.1 ,  2.01,  3.  ,  3.1 ,  3.01,  4.  ,  4.1 ,  4.01,  5.  ,  5.1 ],
       [ 2.  ,  2.1 ,  2.01,  3.  ,  3.1 ,  3.01,  4.  ,  4.1 ,  4.01,  5.  ,  5.1 ,  5.01],
       [ 2.1 ,  2.01,  3.  ,  3.1 ,  3.01,  4.  ,  4.1 ,  4.01,  5.  ,  5.1 ,  5.01,  6.  ],
       [ 2.01,  3.  ,  3.1 ,  3.01,  4.  ,  4.1 ,  4.01,  5.  ,  5.1 ,  5.01,  6.  ,  6.1 ],
       [ 3.  ,  3.1 ,  3.01,  4.  ,  4.1 ,  4.01,  5.  ,  5.1 ,  5.01,  6.  ,  6.1 ,  6.01],
       [ 3.1 ,  3.01,  4.  ,  4.1 ,  4.01,  5.  ,  5.1 ,  5.01,  6.  ,  6.1 ,  6.01,  7.  ],
       [ 3.01,  4.  ,  4.1 ,  4.01,  5.  ,  5.1 ,  5.01,  6.  ,  6.1 ,  6.01,  7.  ,  7.1 ],
       [ 4.  ,  4.1 ,  4.01,  5.  ,  5.1 ,  5.01,  6.  ,  6.1 ,  6.01,  7.  ,  7.1 ,  7.01],
       [ 4.1 ,  4.01,  5.  ,  5.1 ,  5.01,  6.  ,  6.1 ,  6.01,  7.  ,

In [9]:
sliding_window_view(data_np.flatten(), window_shape=4 * 3)[::3]

array([[ 1.  ,  1.1 ,  1.01,  2.  ,  2.1 ,  2.01,  3.  ,  3.1 ,  3.01,  4.  ,  4.1 ,  4.01],
       [ 2.  ,  2.1 ,  2.01,  3.  ,  3.1 ,  3.01,  4.  ,  4.1 ,  4.01,  5.  ,  5.1 ,  5.01],
       [ 3.  ,  3.1 ,  3.01,  4.  ,  4.1 ,  4.01,  5.  ,  5.1 ,  5.01,  6.  ,  6.1 ,  6.01],
       [ 4.  ,  4.1 ,  4.01,  5.  ,  5.1 ,  5.01,  6.  ,  6.1 ,  6.01,  7.  ,  7.1 ,  7.01],
       [ 5.  ,  5.1 ,  5.01,  6.  ,  6.1 ,  6.01,  7.  ,  7.1 ,  7.01,  8.  ,  8.1 ,  8.01],
       [ 6.  ,  6.1 ,  6.01,  7.  ,  7.1 ,  7.01,  8.  ,  8.1 ,  8.01,  9.  ,  9.1 ,  9.01],
       [ 7.  ,  7.1 ,  7.01,  8.  ,  8.1 ,  8.01,  9.  ,  9.1 ,  9.01, 10.  , 10.1 , 10.01],
       [ 8.  ,  8.1 ,  8.01,  9.  ,  9.1 ,  9.01, 10.  , 10.1 , 10.01, 11.  , 11.1 , 11.01],
       [ 9.  ,  9.1 ,  9.01, 10.  , 10.1 , 10.01, 11.  , 11.1 , 11.01, 12.  , 12.1 , 12.01],
       [10.  , 10.1 , 10.01, 11.  , 11.1 , 11.01, 12.  , 12.1 , 12.01, 13.  , 13.1 , 13.01],
       [11.  , 11.1 , 11.01, 12.  , 12.1 , 12.01, 13.  , 13.1 , 13.01,